version: '3.8'

services:
  votebot:
    build: .
    container_name: alturi-votebot
    restart: always
    volumes:
      - ./accounts.json:/app/accounts.json    # Account-Daten
      - ./vote_times.json:/app/vote_times.json  # Vote-Zeiten
      - ./logs:/app/logs                      # Log-Dateien
    environment:
      - TZ=Europe/Berlin
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
